name: MY FIRST GITHUB ACTION

on:
  push:
    branches:
       - master

env:
  NAME: "ABIODUN ADEBISI"
  PROFESSION: "DATA ENTHUSIAST $ MENTAL HEALTH ADVOCATE"
  PASSION: "STUDYING"


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
       - uses: actions/checkout@v2
       - name: Echo Github Actions
         run: echo "Hi, this is $NAME. I am a $PROFESSION by profession and $PASSION my passion"
  post-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: "echo postbuilds steps"
        run: echo "POSTBUILDS STEPS AFTER EXECUTION OF ABOVE STEPS"
